#ifndef CAT_H
#define CAT_H

#include <nl_types.h>

#define USAGE catgets(catd,1,1,"Aufruf: teapot [-a] [-b] [-n] [-r] [-p Stellen] [Datei]\n")
#define OHWELL catgets(catd,1,2,"FEHLER")
#define DIV0 catgets(catd,1,3,"Division durch 0")
#define DIVTYPE catgets(catd,1,4,"Falscher Typ für / Operator")
#define MOD0 catgets(catd,1,5,"Modulo 0")
#define MODTYPE catgets(catd,1,6,"Falscher Typ für % Operator")
#define MULTYPE catgets(catd,1,7,"Falscher Typ für * Operator")
#define ADDTYPE catgets(catd,1,8,"Falscher Typ für + Operator")
#define SUBTYPE catgets(catd,1,9,"Falscher Typ für - Operator")
#define NEGTYPE catgets(catd,1,10,"Falscher Typ für - Operator")
#define POWTYPE catgets(catd,1,11,"Falscher Typ für ^ Operator")
#define MISSOPR catgets(catd,1,12,"Fehlender Operator")
#define TOOMANY catgets(catd,1,13,"Zu viele Argumente")
#define NESTEVAL catgets(catd,1,14,"Verschachtelte eval()s")
#define CPEXPCT catgets(catd,1,15,") erwartet")
#define OPEXPECT catgets(catd,1,16,"( erwartet")
#define VLEXPCT catgets(catd,1,17,"Wert erwartet")
#define PARSERR catgets(catd,1,18,"Parse-Fehler nach Term")
#define NOINT catgets(catd,1,19,"int(Zeichenkette): Ungültige Zeichenkette")
#define INFINT catgets(catd,1,20,"int(Zeichenkette): Bereichsfehler")
#define RELTYPE catgets(catd,1,21,"Falscher Typ für relationalen Operator")
#define NOLABEL catgets(catd,1,22,"Label existiert nicht")
#define NEGLOC catgets(catd,1,23,"Negativer Index")
#define POW00 catgets(catd,1,24,"0^0 ist undefiniert")
#define POWDOM catgets(catd,1,25,"^ verursachte einen Bereichsfehler")
#define ISLOCKED catgets(catd,1,26,"Zelle ist geschützt")
#define NOTAG catgets(catd,1,27,"Unbekanntes 'Tag' %c in Zeile %d")
#define MOVEONLY catgets(catd,1,28,"B")
#define MOVEEDIT catgets(catd,1,29,"Ä")
#define SHADOWBOO2 catgets(catd,1,30,"Versuch Zelle (%d,%d,%d) in Zeile %d zu verdecken")
#define XERR catgets(catd,1,31,"Syntaxfehler der x-Position in Zeile %d")
#define YERR catgets(catd,1,32,"Syntaxfehler der y-Position in Zeile %d")
#define ZERR catgets(catd,1,33,"Syntaxfehler der z-Position in Zeile %d")
#define OPTERR catgets(catd,1,34,"Falsche Option %c in Zeile %d")
#define SYNERR catgets(catd,1,35,"Syntaxfehler im Ausdruck in Zeile %d")
#define WIDTHERR catgets(catd,1,36,"Syntaxfehler der Breite in Zeile %d")
#define PRECERR catgets(catd,1,37,"Syntaxfehler der Genauigkeit in Zeile %d")
#define ADJERR catgets(catd,1,38,"Syntaxfehler in der Ausrichtung in Zeile %d")
#define SCFEATURE catgets(catd,1,39,"Nicht implementiertes SC Feature in Zeile %d")
#define NOTFINITE catgets(catd,1,40,"Keine (endliche) Fließkommazahl")
#define UFLOW catgets(catd,1,41,"Unterhalb des Fließkommabereichs")
#define OFLOW catgets(catd,1,42,"Oberhalb des Fließkommabereichs")
#define UNCOMPAR catgets(catd,1,43,"Elemente nicht vergleichbar")
#define NOREGION catgets(catd,1,44,"Keine Region selektiert")
#define SHELL catgets(catd,1,45,"Shell starten")
#define SUBSHELL catgets(catd,1,46,"Shell gestartet")
#define BACKGROUND catgets(catd,1,47,"Teapot ist gestoppt")
#define NOTSUSPENDED catgets(catd,1,48,"Das susp Zeichen ist nicht gesetzt")
#define BROKENSHEET catgets(catd,1,49,"Ungültiger Datensatz, das Laden wurde abgebrochen")
#define WRONGXDRMAGIC catgets(catd,1,50,"Dies ist kein Teapot Arbeitsblatt im XDR Format")
#define TRUNCHEADER catgets(catd,1,51,"Der Kopf eines Datensatzes ist abgeschnitten")
#define TRUNCBODY catgets(catd,1,52,"Der Rumpf eines Datensatzes ist abgeschnitten")
#define NOBOF catgets(catd,1,53,"Dies ist keine WK1 Datei")
#define NOEOF catgets(catd,1,54,"Datei endet unerwartet")
#define INVALIDBODYLEN catgets(catd,1,55,"Die Länge eines Datensatzes ist falsch")
#define NOMEM catgets(catd,1,56,"Es steht nicht mehr genügend Speicher zur Verfügung")
#define YES catgets(catd,1,57,"jJ)a")
#define NO catgets(catd,1,58,"nN)ein")
#define ADJUST catgets(catd,1,59,"rR)epräsentation")
#define ADLEFT catgets(catd,1,60,"lL)inks")
#define ADRIGHT catgets(catd,1,61,"rR)echts")
#define ADCENTERED catgets(catd,1,62,"zZ)entriert")
#define PRECISION catgets(catd,1,63,"gG)enauigkeit")
#define DOLOCK catgets(catd,1,64,"sS)chützen")
#define DOIGNORE catgets(catd,1,65,"iI)gnorieren")
#define DOSCI catgets(catd,1,66,"00).123e1")
#define NOSCI catgets(catd,1,67,"11).23")
#define LABEL catgets(catd,1,68,"mM)arke")
#define ASXDR catgets(catd,1,69,"xX)DR")
#define ASASCII catgets(catd,1,70,"aA)SCII")
#define ASSC catgets(catd,1,71,"sS)C")
#define ASWK1 catgets(catd,1,72,"wW)K1")
#define TBL catgets(catd,1,73,"tT)bl")
#define LATEX catgets(catd,1,74,"lL)aTeX")
#define HTML catgets(catd,1,75,"hH)TML")
#define CSV catgets(catd,1,76,"cC)SV")
#define GCSV catgets(catd,1,77,"cG)CSV")
#define SAVETEXT catgets(catd,1,78,"fF)ormatierter Text")
#define CONTEXT catgets(catd,1,79,"oCo)nTeXt")
#define LOAD catgets(catd,1,80,"lL)aden")
#define SAVE catgets(catd,1,81,"sS)peichern")
#define NAME catgets(catd,1,82,"dD)ateiname")
#define FILER catgets(catd,1,83,"dD)atei")
#define QUIT catgets(catd,1,84,"eE)nde")
#define ATTR catgets(catd,1,85,"aA)ttribute")
#define SHADOW catgets(catd,1,86,"vV)erdecken")
#define TRANSPAR catgets(catd,1,87,"sS)onderzeichen ausgeben")
#define INX catgets(catd,1,88,"sS)palte")
#define INY catgets(catd,1,89,"zZ)eile")
#define INZ catgets(catd,1,90,"tT)iefe")
#define INSERT catgets(catd,1,91,"iEi)nfügen")
#define CLEAR catgets(catd,1,92,"zZ)elle löschen")
#define MOVE catgets(catd,1,93,"vV)erschieben")
#define COPY catgets(catd,1,94,"kK)opieren")
#define FILL catgets(catd,1,95,"fF)üllen")
#define MIRROR catgets(catd,1,96,"sS)piegeln")
#define TOMENU catgets(catd,1,97,"F0, F10 oder / für Menü")
#define ABOUT catgets(catd,1,98,"vV)ersion")
#define MSHELL catgets(catd,1,99,"sS)hell")
#define MGOTO catgets(catd,1,100,"pP)osition")
#define CWIDTH catgets(catd,1,101,"sS)paltenbreite")
#define DELETE catgets(catd,1,102,"eE)ntfernen")
#define SORT catgets(catd,1,103,"sS)ortieren")
#define ADDKEY catgets(catd,1,104,"hTaste h)inzufügen")
#define ASCEND catgets(catd,1,105,"--) aufsteigend")
#define DESCEND catgets(catd,1,106,"++) absteigend")
#define SORTIT catgets(catd,1,107,"sBereich s)ortieren")
#define WHOLECOL catgets(catd,1,108,"gG)anze Spalte")
#define WHOLELINE catgets(catd,1,109,"gG)anze Zeile")
#define WHOLELAYER catgets(catd,1,110,"gG)anzes Blatt")
#define SINGLECELL catgets(catd,1,111,"eE)inzelne Zelle")
#define BLOCK catgets(catd,1,112,"bB)lock")
#define LOADXSHEET catgets(catd,1,113,"Arbeitsblatt als XDR Datei laden:")
#define LOADPSHEET catgets(catd,1,114,"Arbeitsblatt als ASCII Datei laden:")
#define LOADCSVSHEET catgets(catd,1,115,"Arbeitsblatt als CSV Datei laden:")
#define LOADSCSHEET catgets(catd,1,116,"Arbeitsblatt als SC Datei laden:")
#define LOADWK1SHEET catgets(catd,1,117,"Arbeitsblatt als WK1 Datei laden:")
#define SAVEXSHEET catgets(catd,1,118,"Arbeitsblatt als XDR File speichern:")
#define WROTECELLS catgets(catd,1,119,"%u Zellen gespeichert")
#define SAVEPSHEET catgets(catd,1,120,"Arbeitsblatt als ASCII File speichern:")
#define SAVEMENU catgets(catd,1,121,"Format der zu speichernden Datei:")
#define LOADMENU catgets(catd,1,122,"Format der zu ladenden Datei:")
#define NAMESHEET catgets(catd,1,123,"Neuer Dateiname:")
#define FILERMENU catgets(catd,1,124,"Datei:")
#define LOADANYWAY catgets(catd,1,125,"Das Arbeitsblatt ist verändert, trotzdem eine neue Datei laden?")
#define LEAVE catgets(catd,1,126,"Das Arbeitsblatt ist verändert, trotzdem beenden?")
#define MAINMENU catgets(catd,1,127,"Hauptmenü:")
#define COLWIDTH catgets(catd,1,128,"Spaltenbreite:")
#define CELLATTR catgets(catd,1,129,"Zellenattribute:")
#define SHADOWCELL catgets(catd,1,130,"Zelle verdecken:")
#define TRANSCELL catgets(catd,1,131,"Sonderzeichen in dieser Zelle ausgeben:")
#define TRANSCUBE catgets(catd,1,132,"Sonderzeichen in diesem Block ausgeben:")
#define CONTENTS catgets(catd,1,133,"Zelleninhalt:")
#define CCONTENTS catgets(catd,1,134,"Getakteter Zelleninhalt:")
#define GOTO catgets(catd,1,135,"Cursor auf Position:")
#define LOCBOO catgets(catd,1,136,"Keine gültige Position")
#define SHADOWBOO catgets(catd,1,137,"Zellen in Spalte 0 können nicht verdeckt werden")
#define WHAT catgets(catd,1,138,"Unbekannter Batch-Befehl:")
#define PRECCELL catgets(catd,1,139,"Genauigkeit der Zelle:")
#define PRECBLOCK catgets(catd,1,140,"Genauigkeit des Blocks:")
#define SAVETEXTF catgets(catd,1,141,"Speichere Datei im Text-Format:")
#define SAVECSVF catgets(catd,1,142,"Speichere Datei im CSV-Format:")
#define SAVETBLF catgets(catd,1,143,"Speichere Datei im tbl-Format:")
#define SAVELATEXF catgets(catd,1,144,"Speichere Datei im LaTex-Format:")
#define SAVEHTMLF catgets(catd,1,145,"Speichere Datei im HTML-Format:")
#define SAVECONTEXTF catgets(catd,1,146,"Speichere Datei im ConTeXt-Format:")
#define BLOCKATTR catgets(catd,1,147,"Block Attribut:")
#define CLEARBLOCK catgets(catd,1,148,"Block löschen:")
#define CLEARCELL catgets(catd,1,149,"Zelle löschen:")
#define SHADOWCUBE catgets(catd,1,150,"Block verdecken:")
#define INSERTBLOCK catgets(catd,1,151,"Einfügen:")
#define DELETEBLOCK catgets(catd,1,152,"Entfernen:")
#define MODIFYCELL catgets(catd,1,153,"Zelle editieren:")
#define LOCKCELL catgets(catd,1,154,"Zelle schützen:")
#define LOCKBLOCK catgets(catd,1,155,"Block schützen:")
#define IGNCELL catgets(catd,1,156,"Wert der Zelle ignorieren:")
#define IGNBLOCK catgets(catd,1,157,"Werte aller Zellen des Blockes ignorieren:")
#define DOLABEL catgets(catd,1,158,"Zellen Marke:")
#define MOVEBLOCK catgets(catd,1,159,"Block verschieben:")
#define NOMARK catgets(catd,1,160,"Kein Block markiert")
#define COPYBLOCK catgets(catd,1,161,"Block kopieren:")
#define FILLBLOCK catgets(catd,1,162,"Block füllen:")
#define FILLCOLS catgets(catd,1,163,"Anzahl der spaltenweisen Wiederholungen:")
#define FILLROWS catgets(catd,1,164,"Anzahl der zeilenweisen Wiederholungen:")
#define FILLLAYERS catgets(catd,1,165,"Anzahl der Wiederholungen in die Tiefe:")
#define SORTBLOCK catgets(catd,1,166,"Block sortieren:")
#define XPOS catgets(catd,1,167,"X-Position der Schlüsselvektoren:")
#define YPOS catgets(catd,1,168,"Y-Position der Schlüsselvektoren:")
#define ZPOS catgets(catd,1,169,"Z-Position der Schlüsselvektoren:")
#define MIRRORBLOCK catgets(catd,1,170,"Block spiegeln:")
#define LEFTRIGHT catgets(catd,1,171,"lL)inks-rechts")
#define UPSIDEDOWN catgets(catd,1,172,"oO)ben-unten")
#define FRONTBACK catgets(catd,1,173,"vV)orn-hinten")
#define STANDALONE catgets(catd,1,174,"Speicher als alleinstehendes Dokument:")
#define BLOCKMENU catgets(catd,1,175,"Block Menü:")
#define NOSHADOW catgets(catd,1,176,"Verdeckte Zellen in der ersten Spalte")
#define INVALPRECISION catgets(catd,1,177,"teapot: Die Genauigkeit muß zwischen 0 und %d liegen.\n")
#define USAGE_ERROR catgets(catd,1,178,"Aufruf: error(Zeichenkette Nachricht)")
#define USAGE_ADR catgets(catd,1,179,"Aufruf: &([Ganzzahl x][,[Ganzzahl y][,[Ganzzahl z]]])")
#define USAGE_AT catgets(catd,1,180,"Aufruf: @([Ganzzahl x][,[Ganzzahl y][,[Ganzzahl z]]]) oder @(Position)")
#define XTYPE catgets(catd,1,181,"Aufruf: x([Position])")
#define YTYPE catgets(catd,1,182,"Aufruf: y([Position])")
#define ZTYPE catgets(catd,1,183,"Aufruf: z([Position])")
#define STRINGTYPE catgets(catd,1,184,"Aufruf: string(Position) oder string(Fließkommazahl[,[Ganzzahl][,Ganzzahl]])")
#define SUMTYPE catgets(catd,1,185,"Aufruf: sum(Position,Position)")
#define NTYPE catgets(catd,1,186,"Aufruf: n(Position,Position)")
#define INTTYPE catgets(catd,1,187,"Aufruf: int(Fließkommazahl[,Ganzzahl,Ganzzahl])")
#define FRACTYPE catgets(catd,1,188,"Aufruf: frac(Fließkommazahl)")
#define LENTYPE catgets(catd,1,189,"Aufruf: len(Zeichenkette)")
#define MINTYPE catgets(catd,1,190,"Aufruf: min(Position,Position)")
#define MAXTYPE catgets(catd,1,191,"Aufruf: max(Position,Position)")
#define ABSTYPE catgets(catd,1,192,"Aufruf: abs(Fließkommazahl|Ganzzahl)")
#define USAGE_EVAL catgets(catd,1,193,"Aufruf: eval(Position)")
#define USAGE_ENV catgets(catd,1,194,"Aufruf: $(Zeichenkette)")
#define FLOATTYPE catgets(catd,1,195,"Aufruf: float(Zeichenkette)")
#define STRFTIMETYPE catgets(catd,1,196,"Aufruf: strftime(Zeichenkette[,Ganzzahl])")
#define CLOCK catgets(catd,1,197,"Aufruf: clock(Bedingung,Position[,Position])")
#define POLYTYPE catgets(catd,1,198,"Aufruf: poly(Fließkommazahl|Ganzzahl,Fließkommazahl|Ganzzahl,...)")
#define ETYPE catgets(catd,1,199,"Aufruf: e()")
#define LOGTYPE catgets(catd,1,200,"Aufruf: log(Fließkommazahl[,Fließkommazahl])")
#define WRONGTYPE catgets(catd,1,201,"Aufruf: %s(Fließkommazahl)")
#define USAGE_RND catgets(catd,1,202,"Aufruf: rnd()")
#define USAGE_SUBSTR catgets(catd,1,203,"Aufruf: substr(Zeichenkette,Ganzzahl,Ganzzahl)")
#define STRPTIMETYPE catgets(catd,1,204,"Aufruf: strptime(Zeichenkette,Zeichenkette)")
#define USAGE_TIME catgets(catd,1,205,"Aufruf: time()")

#endif
