#ifndef CAT_H
#define CAT_H

#include <nl_types.h>

#define USAGE catgets(catd,1,1,"Gebruik: teapot [-a] [-b] [-n] [-r] [-p cijfers] [bestand]\n")
#define OHWELL catgets(catd,1,2,"FOUTJE")
#define DIV0 catgets(catd,1,3,"Deling door 0")
#define DIVTYPE catgets(catd,1,4,"Verkeerd type voor de / operator")
#define MOD0 catgets(catd,1,5,"Modulo 0")
#define MODTYPE catgets(catd,1,6,"Verkeerd type voor de % operator")
#define MULTYPE catgets(catd,1,7,"Verkeerd type voor de * operator")
#define ADDTYPE catgets(catd,1,8,"Verkeerd type voor de + operator")
#define SUBTYPE catgets(catd,1,9,"Verkeerd type voor de - operator")
#define NEGTYPE catgets(catd,1,10,"Verkeerd type voor de - operator")
#define POWTYPE catgets(catd,1,11,"Verkeerd type voor de ^ operator")
#define MISSOPR catgets(catd,1,12,"Ontbrekende operator")
#define TOOMANY catgets(catd,1,13,"Teveel argumenten")
#define NESTEVAL catgets(catd,1,14,"Geneste eval()s")
#define CPEXPCT catgets(catd,1,15,") verwacht")
#define OPEXPECT catgets(catd,1,16,"( verwacht")
#define VLEXPCT catgets(catd,1,17,"Waarde verwacht")
#define PARSERR catgets(catd,1,18,"Ontleedfout na term")
#define NOINT catgets(catd,1,19,"int(letterrij): ongeldige letterrij")
#define INFINT catgets(catd,1,20,"int(letterrij): buiten bereik")
#define RELTYPE catgets(catd,1,21,"Verkeerd type voor relationele operator")
#define NOLABEL catgets(catd,1,22,"Label bestaat niet")
#define NEGLOC catgets(catd,1,23,"Negatieve index")
#define POW00 catgets(catd,1,24,"0^0 is niet gedefinieerd")
#define POWDOM catgets(catd,1,25,"^ veroorzaakte een bereikfout")
#define ISLOCKED catgets(catd,1,26,"Cel is geblokkeerd")
#define NOTAG catgets(catd,1,27,"Onbekend teken %c in regel %d")
#define MOVEONLY catgets(catd,1,28,"V")
#define MOVEEDIT catgets(catd,1,29,"E")
#define SHADOWBOO2 catgets(catd,1,30,"Proberen cel (%d,%d,%d) in regel %d te bedekken")
#define XERR catgets(catd,1,31,"Syntaxfout voor de x-positie in regel %d")
#define YERR catgets(catd,1,32,"Syntaxfout voor de y-positie in regel %d")
#define ZERR catgets(catd,1,33,"Syntaxfout voor de z-positie in regel %d")
#define OPTERR catgets(catd,1,34,"Verkeerde optie %c in regel %d")
#define SYNERR catgets(catd,1,35,"Syntaxfout in de expressie in regel %d")
#define WIDTHERR catgets(catd,1,36,"Syntaxfout voor de breedte in regel %d")
#define PRECERR catgets(catd,1,37,"Syntaxfout voor de nauwkeurigheid in regel %d")
#define ADJERR catgets(catd,1,38,"Syntaxfout voor de aanpassing in regel %d")
#define SCFEATURE catgets(catd,1,39,"Niet-geimplementeerd SC-mogelijkheid in regel %d")
#define NOTFINITE catgets(catd,1,40,"Niet een (eindig) schuivendekomma-getal")
#define UFLOW catgets(catd,1,41,"Te klein voor het bereik van de schuivende komma")
#define OFLOW catgets(catd,1,42,"Te groot voor het bereik van de schuivende komma")
#define UNCOMPAR catgets(catd,1,43,"Elementen niet vergelijkbaar")
#define NOREGION catgets(catd,1,44,"Geen regio geselecteerd")
#define SHELL catgets(catd,1,45,"Shell opstarten")
#define SUBSHELL catgets(catd,1,46,"Shell gestart")
#define BACKGROUND catgets(catd,1,47,"Teapot is gestopt")
#define NOTSUSPENDED catgets(catd,1,48,"Het susp-teken is niet gedefinieerd")
#define BROKENSHEET catgets(catd,1,49,"Verkeerde dataset. Het inlezen is gestopt")
#define WRONGXDRMAGIC catgets(catd,1,50,"Dit is geen teapot-werkblad in XDR-formaat")
#define TRUNCHEADER catgets(catd,1,51,"Het begin van de dataset is onderbroken")
#define TRUNCBODY catgets(catd,1,52,"Het midden van de dataset is onderbroken")
#define NOBOF catgets(catd,1,53,"Dit is geen WK1-bestand")
#define NOEOF catgets(catd,1,54,"Het bestand is onderbroken")
#define INVALIDBODYLEN catgets(catd,1,55,"Het bestand is te lang of te kort")
#define NOMEM catgets(catd,1,56,"Geen geheugen meer ter beschikking")
#define YES catgets(catd,1,57,"jJ)a")
#define NO catgets(catd,1,58,"nN)een")
#define ADJUST catgets(catd,1,59,"wW)eergave")
#define ADLEFT catgets(catd,1,60,"lL)inks")
#define ADRIGHT catgets(catd,1,61,"rR)echts")
#define ADCENTERED catgets(catd,1,62,"cgeC)entreerd")
#define PRECISION catgets(catd,1,63,"pP)recisie")
#define DOLOCK catgets(catd,1,64,"bB)lokkeren")
#define DOIGNORE catgets(catd,1,65,"nN)egeren")
#define DOSCI catgets(catd,1,66,"00).123e1")
#define NOSCI catgets(catd,1,67,"11).23")
#define LABEL catgets(catd,1,68,"lL)abel")
#define ASXDR catgets(catd,1,69,"xX)DR")
#define ASASCII catgets(catd,1,70,"aA)SCII")
#define ASSC catgets(catd,1,71,"sS)C")
#define ASWK1 catgets(catd,1,72,"wW)K1")
#define TBL catgets(catd,1,73,"tT)bl")
#define LATEX catgets(catd,1,74,"lL)aTex")
#define HTML catgets(catd,1,75,"hH)TML")
#define CSV catgets(catd,1,76,"cC)SV")
#define GCSV catgets(catd,1,77,"cG)CSV")
#define SAVETEXT catgets(catd,1,78,"fgeF)ormateerde tekst")
#define CONTEXT catgets(catd,1,79,"oCo)nTeXt")
#define LOAD catgets(catd,1,80,"iI)nlezen")
#define SAVE catgets(catd,1,81,"oO)pslaan")
#define NAME catgets(catd,1,82,"nN)aam")
#define FILER catgets(catd,1,83,"bB)estand")
#define QUIT catgets(catd,1,84,"eE)inde")
#define ATTR catgets(catd,1,85,"aA)ttributen")
#define SHADOW catgets(catd,1,86,"bB)edekken")
#define TRANSPAR catgets(catd,1,87,"sS)peciale tekens aangeven")
#define INX catgets(catd,1,88,"kK)olom")
#define INY catgets(catd,1,89,"rR)egel")
#define INZ catgets(catd,1,90,"dD)iepte")
#define INSERT catgets(catd,1,91,"iI)nvoegen")
#define CLEAR catgets(catd,1,92,"sS)choonvegen")
#define MOVE catgets(catd,1,93,"vV)erschuiven")
#define COPY catgets(catd,1,94,"cC)opieren")
#define FILL catgets(catd,1,95,"vV)ullen")
#define MIRROR catgets(catd,1,96,"XXX")
#define TOMENU catgets(catd,1,97,"Gebruik F0, F10 of / voor het menu")
#define ABOUT catgets(catd,1,98,"vV)ersie")
#define MSHELL catgets(catd,1,99,"sS)hell")
#define MGOTO catgets(catd,1,100,"pP)ositie")
#define CWIDTH catgets(catd,1,101,"kK)olombreedte")
#define DELETE catgets(catd,1,102,"uU)itvegen")
#define SORT catgets(catd,1,103,"sS)orteren")
#define ADDKEY catgets(catd,1,104,"tT)oets tT)oevoegen")
#define ASCEND catgets(catd,1,105,"sS)tijgend")
#define DESCEND catgets(catd,1,106,"dD)alend")
#define SORTIT catgets(catd,1,107,"sS)orteren van regio")
#define WHOLECOL catgets(catd,1,108,"gG)ehele kolom")
#define WHOLELINE catgets(catd,1,109,"gG)ehele regel")
#define WHOLELAYER catgets(catd,1,110,"gG)ehele werkblad")
#define SINGLECELL catgets(catd,1,111,"eE)en losse cel")
#define BLOCK catgets(catd,1,112,"bB)lok")
#define LOADXSHEET catgets(catd,1,113,"Inlezen werkblad uit XDR-bestand:")
#define LOADPSHEET catgets(catd,1,114,"Inlezen werkblad uit ASCII-bestand:")
#define LOADCSVSHEET catgets(catd,1,115,"Inlezen werkblad uit CSV-bestand:")
#define LOADSCSHEET catgets(catd,1,116,"Inlezen werkblad uit SC-bestand:")
#define LOADWK1SHEET catgets(catd,1,117,"Inlezen werkblad uit WK1-bestand:")
#define SAVEXSHEET catgets(catd,1,118,"Opslaan werkblad als XDR-bestand:")
#define WROTECELLS catgets(catd,1,119,"%u cellen opgeslagen")
#define SAVEPSHEET catgets(catd,1,120,"Opslaan werkblad als ASCII-bestand:")
#define SAVEMENU catgets(catd,1,121,"Bestandsformaat om in op te slaan:")
#define LOADMENU catgets(catd,1,122,"Bestandsformaat om in te lezen:")
#define NAMESHEET catgets(catd,1,123,"Nieuwe bestandsnaam:")
#define FILERMENU catgets(catd,1,124,"Bestand:")
#define LOADANYWAY catgets(catd,1,125,"Het werkblad is veranderd. Toch een nieuw bestand inlezen?")
#define LEAVE catgets(catd,1,126,"Het werkblad is veranderd. Toch eindigen?")
#define MAINMENU catgets(catd,1,127,"Hoofdmenu:")
#define COLWIDTH catgets(catd,1,128,"Kolombreedte")
#define CELLATTR catgets(catd,1,129,"Celattribuut:")
#define SHADOWCELL catgets(catd,1,130,"Cel bedekken:")
#define TRANSCELL catgets(catd,1,131,"Cel transparant maken:")
#define TRANSCUBE catgets(catd,1,132,"Blok transparant maken:")
#define CONTENTS catgets(catd,1,133,"Celinhoud:")
#define CCONTENTS catgets(catd,1,134,"Geklokte celinhoud:")
#define GOTO catgets(catd,1,135,"Cursor op positie:")
#define LOCBOO catgets(catd,1,136,"Geen geldige positie")
#define SHADOWBOO catgets(catd,1,137,"Cellen in kolom 0 kunnen niet bedekt worden")
#define WHAT catgets(catd,1,138,"Onbekend batch-commando:")
#define PRECCELL catgets(catd,1,139,"Precisie voor de cel:")
#define PRECBLOCK catgets(catd,1,140,"Precisie voor het blok:")
#define SAVETEXTF catgets(catd,1,141,"Opslaan in tekstformaat in bestand:")
#define SAVECSVF catgets(catd,1,142,"Opslaan in CSV-formaat in bestand:")
#define SAVETBLF catgets(catd,1,143,"Opslaan in tbl-formaat in bestand:")
#define SAVELATEXF catgets(catd,1,144,"Opslaan in LaTeX-formaat in bestand:")
#define SAVEHTMLF catgets(catd,1,145,"Opslaan in HTML-formaat in bestand:")
#define SAVECONTEXTF catgets(catd,1,146,"Opslaan in ConTeXt-formaat in bestand:")
#define BLOCKATTR catgets(catd,1,147,"Blokattribuut:")
#define CLEARBLOCK catgets(catd,1,148,"Blok uitvegen:")
#define CLEARCELL catgets(catd,1,149,"Cel uitvegen:")
#define SHADOWCUBE catgets(catd,1,150,"Blok bedekken:")
#define INSERTBLOCK catgets(catd,1,151,"Invoegen:")
#define DELETEBLOCK catgets(catd,1,152,"Uitvegen:")
#define MODIFYCELL catgets(catd,1,153,"Cel aanpassen:")
#define LOCKCELL catgets(catd,1,154,"Cel blokkeren:")
#define LOCKBLOCK catgets(catd,1,155,"Blok blokkeren:")
#define IGNCELL catgets(catd,1,156,"Waarde van de cel negeren:")
#define IGNBLOCK catgets(catd,1,157,"Waardes van alle cellen in dit blok negeren:")
#define DOLABEL catgets(catd,1,158,"Cel label:")
#define MOVEBLOCK catgets(catd,1,159,"Blok verschuiven:")
#define NOMARK catgets(catd,1,160,"Geen blok aangegeven")
#define COPYBLOCK catgets(catd,1,161,"Blok copieren:")
#define FILLBLOCK catgets(catd,1,162,"Blok vullen:")
#define FILLCOLS catgets(catd,1,163,"Aantal kolomgewijze herhalingen:")
#define FILLROWS catgets(catd,1,164,"Aantal regelgewijze herhalingen:")
#define FILLLAYERS catgets(catd,1,165,"Aantal herhalingen in de diepte:")
#define SORTBLOCK catgets(catd,1,166,"Blok sorteren:")
#define XPOS catgets(catd,1,167,"X-positie van de sleutelvector:")
#define YPOS catgets(catd,1,168,"Y-positie van de sleutelvector:")
#define ZPOS catgets(catd,1,169,"Z-positie van de sleutelvector:")
#define MIRRORBLOCK catgets(catd,1,170,"Blok XXX:")
#define LEFTRIGHT catgets(catd,1,171,"XXX")
#define UPSIDEDOWN catgets(catd,1,172,"XXX")
#define FRONTBACK catgets(catd,1,173,"XXX")
#define STANDALONE catgets(catd,1,174,"Opslaan als losstaand document:")
#define BLOCKMENU catgets(catd,1,175,"Blokmenu:")
#define NOSHADOW catgets(catd,1,176,"Bedekte cellen in de eerste kolom")
#define INVALPRECISION catgets(catd,1,177,"teapot: De nauwkeurigheid moet tussen 0 en %d zijn.\n")
#define USAGE_ERROR catgets(catd,1,178,"Gebruik: error(letterrij bericht)")
#define USAGE_ADR catgets(catd,1,179,"Gebruik: &([integer x][,[integer y][,[integer z]]])")
#define USAGE_AT catgets(catd,1,180,"Gebruik: @([integer x][,[integer y][,[integer z]]]) of @(positie)")
#define XTYPE catgets(catd,1,181,"Gebruik: x([positie])")
#define YTYPE catgets(catd,1,182,"Gebruik: y([positie])")
#define ZTYPE catgets(catd,1,183,"Gebruik: z([positie])")
#define STRINGTYPE catgets(catd,1,184,"Gebruik: string(positie) of string(float[,[integer][,integer]])")
#define SUMTYPE catgets(catd,1,185,"Gebruik: sum(positie,positie)")
#define NTYPE catgets(catd,1,186,"Gebruik: n(positie,positie)")
#define INTTYPE catgets(catd,1,187,"Gebruik: int(float[,integer,integer])")
#define FRACTYPE catgets(catd,1,188,"Gebruik: frac(float)")
#define LENTYPE catgets(catd,1,189,"Gebruik: len(letterrij)")
#define MINTYPE catgets(catd,1,190,"Gebruik: min(positie,positie)")
#define MAXTYPE catgets(catd,1,191,"Gebruik: max(positie,positie)")
#define ABSTYPE catgets(catd,1,192,"Gebruik: abs(float|integer)")
#define USAGE_EVAL catgets(catd,1,193,"Gebruik: eval(positie)")
#define USAGE_ENV catgets(catd,1,194,"Gebruik: $(letterrij)")
#define FLOATTYPE catgets(catd,1,195,"Gebruik: float(letterrij)")
#define STRFTIMETYPE catgets(catd,1,196,"Gebruik: strftime(letterrij[,integer])")
#define CLOCK catgets(catd,1,197,"Gebruik: clock(conditie,positie[,positie])")
#define POLYTYPE catgets(catd,1,198,"Gebruik: poly(float|integer,float|integer,...)")
#define ETYPE catgets(catd,1,199,"Gebruik: e()")
#define LOGTYPE catgets(catd,1,200,"Gebruik: log(float[,float])")
#define WRONGTYPE catgets(catd,1,201,"Gebruik: %s(float)")
#define USAGE_RND catgets(catd,1,202,"Gebruik: rnd()")
#define USAGE_SUBSTR catgets(catd,1,203,"Gebruik: substr(letterrij,integer,integer)")
#define STRPTIMETYPE catgets(catd,1,204,"Gebruik: strptime(letterrij,letterrij)")
#define USAGE_TIME catgets(catd,1,205,"Gebruik: time()")

#endif
