#ifndef CAT_H
#define CAT_H

#include <nl_types.h>

#define USAGE catgets(catd,1,1,"Uruchomienie: teapot [-a] [-b] [-n] [-r] [-p ile_miejsc] [plik]\n")
#define OHWELL catgets(catd,1,2,"B£¡D")
#define DIV0 catgets(catd,1,3,"Dzielenie przez 0")
#define DIVTYPE catgets(catd,1,4,"Niew³a¶ciwy typ dla operatora /")
#define MOD0 catgets(catd,1,5,"Modulo 0")
#define MODTYPE catgets(catd,1,6,"Niew³a¶ciwe typy dla operatora %")
#define MULTYPE catgets(catd,1,7,"Niew³a¶ciwe typy dla operatora *")
#define ADDTYPE catgets(catd,1,8,"Niew³a¶ciwe typy dla operatora +")
#define SUBTYPE catgets(catd,1,9,"Niew³a¶ciwe typy dla operatora -")
#define NEGTYPE catgets(catd,1,10,"Niew³a¶ciwy typ dla operatora -")
#define POWTYPE catgets(catd,1,11,"Niew³a¶ciwe typy dla operatora ^")
#define MISSOPR catgets(catd,1,12,"Brak operatora")
#define TOOMANY catgets(catd,1,13,"Zbyt wiele argumentów")
#define NESTEVAL catgets(catd,1,14,"Zagnie¿d¿ony eval()")
#define CPEXPCT catgets(catd,1,15,"oczekuje siê znaku )")
#define OPEXPECT catgets(catd,1,16,"oczekuje siê znaku (")
#define VLEXPCT catgets(catd,1,17,"oczekuje siê warto¶ci")
#define PARSERR catgets(catd,1,18,"B³±d parsera w odpowiedzi na wyra¿enie")
#define NOINT catgets(catd,1,19,"int(litera³): ³añcuch znaków niedozwolonej postaci")
#define INFINT catgets(catd,1,20,"int(litera³): b³±d zakresu")
#define RELTYPE catgets(catd,1,21,"niew³a¶ciwy typ dla operatora relacji")
#define NOLABEL catgets(catd,1,22,"nieistniej±ca etykieta")
#define NEGLOC catgets(catd,1,23,"indeks ujemny")
#define POW00 catgets(catd,1,24,"brak definicji 0^0")
#define POWDOM catgets(catd,1,25,"^ wywo³a³a b³±d zakresu")
#define ISLOCKED catgets(catd,1,26,"Komórka zabezpieczona")
#define NOTAG catgets(catd,1,27,"Nieznany 'Tag' %c w wierszu %d")
#define MOVEONLY catgets(catd,1,28,"B")
#define MOVEEDIT catgets(catd,1,29,"Ä")
#define SHADOWBOO2 catgets(catd,1,30,"Próba przykrycia komórki (%d,%d,%d) w wierszu %d")
#define XERR catgets(catd,1,31,"B³±d sk³adniowy na pozycji x w wierszu %d")
#define YERR catgets(catd,1,32,"B³±d sk³adniowy na pozycji y w wierszu %d")
#define ZERR catgets(catd,1,33,"B³±d sk³adniowy na pozycji z w wierszu %d")
#define OPTERR catgets(catd,1,34,"Niedopuszczalna opcja %c w wierszu %d")
#define SYNERR catgets(catd,1,35,"B³±d sk³adniowy wyra¿enia w wierszu %d")
#define WIDTHERR catgets(catd,1,36,"B³±d sk³adniowy przy podaniu szeroko¶ci w wierszu %d")
#define PRECERR catgets(catd,1,37,"B³±d sk³adniowy przy podaniu precyzji w wierszu %d")
#define ADJERR catgets(catd,1,38,"B³±d sk³adniowy przy podaniu po³o¿enia w wierszu %d")
#define SCFEATURE catgets(catd,1,39,"Niezaimplementowana mo¿liwo¶æ SC w wierszu %d")
#define NOTFINITE catgets(catd,1,40,"To nie jest (skoñczona) liczba zmiennoprzecinkowa")
#define UFLOW catgets(catd,1,41,"Poni¿ej zakresu liczb zmiennoprzecinkowych")
#define OFLOW catgets(catd,1,42,"Przekroczony zakres liczb zmiennoprzecinkowych")
#define UNCOMPAR catgets(catd,1,43,"Elementy nieporównywalne")
#define NOREGION catgets(catd,1,44,"Nie wybrano ¿adnego regionu")
#define SHELL catgets(catd,1,45,"Uruchomienie pow³oki")
#define SUBSHELL catgets(catd,1,46,"Pow³oka uruchomiona")
#define BACKGROUND catgets(catd,1,47,"Praca Teapot-a wstrzymana")
#define NOTSUSPENDED catgets(catd,1,48,"Niezdefiniowany znak susp")
#define BROKENSHEET catgets(catd,1,49,"Rekord o b³êdnej postaci, zaniechano wczytania")
#define WRONGXDRMAGIC catgets(catd,1,50,"To nie jest arkusz Teapot-a w formacie XDR")
#define TRUNCHEADER catgets(catd,1,51,"Skrócony nag³ówek rekordu")
#define TRUNCBODY catgets(catd,1,52,"Brak czê¶ci zawarto¶ci rekordu")
#define NOBOF catgets(catd,1,53,"To nie jest plik WK1")
#define NOEOF catgets(catd,1,54,"Brak czê¶ci pliku")
#define INVALIDBODYLEN catgets(catd,1,55,"Niew³a¶ciwy rozmiar zawarto¶ci rekordu")
#define NOMEM catgets(catd,1,56,"Zbyt ma³o wolnej pamiêci")
#define YES catgets(catd,1,57,"tT)ak")
#define NO catgets(catd,1,58,"nN)ie")
#define ADJUST catgets(catd,1,59,"rR)eprezentacja")
#define ADLEFT catgets(catd,1,60,"lL)ewo")
#define ADRIGHT catgets(catd,1,61,"pP)rawo")
#define ADCENTERED catgets(catd,1,62,"cC)entruj")
#define PRECISION catgets(catd,1,63,"dD)ok³adno¶æ")
#define DOLOCK catgets(catd,1,64,"zZ)abezpiecz")
#define DOIGNORE catgets(catd,1,65,"iI)gnoruj")
#define DOSCI catgets(catd,1,66,"00).123e1")
#define NOSCI catgets(catd,1,67,"11).23")
#define LABEL catgets(catd,1,68,"eE)tykieta")
#define ASXDR catgets(catd,1,69,"xX)DR")
#define ASASCII catgets(catd,1,70,"aA)SCII")
#define ASSC catgets(catd,1,71,"sS)C")
#define ASWK1 catgets(catd,1,72,"wW)K1")
#define TBL catgets(catd,1,73,"tT)bl")
#define LATEX catgets(catd,1,74,"lL)aTeX")
#define HTML catgets(catd,1,75,"hH)TML")
#define CSV catgets(catd,1,76,"cC)SV")
#define GCSV catgets(catd,1,77,"cG)CSV")
#define SAVETEXT catgets(catd,1,78,"fF)ormatowany tekst")
#define CONTEXT catgets(catd,1,79,"oCo)nTeXt")
#define LOAD catgets(catd,1,80,"wW)czytaj")
#define SAVE catgets(catd,1,81,"zZ)apisz")
#define NAME catgets(catd,1,82,"nN)azwa pliku")
#define FILER catgets(catd,1,83,"pP)lik")
#define QUIT catgets(catd,1,84,"kK)oniec pracy")
#define ATTR catgets(catd,1,85,"aA)trybuty")
#define SHADOW catgets(catd,1,86,"uU)kryj")
#define TRANSPAR catgets(catd,1,87,"wW)prowad¼ znak specjalny")
#define INX catgets(catd,1,88,"kK)olumna")
#define INY catgets(catd,1,89,"wW)iersz")
#define INZ catgets(catd,1,90,"gG)³êboko¶æ")
#define INSERT catgets(catd,1,91,"wW)staw")
#define CLEAR catgets(catd,1,92,"uU)suñ komórkê")
#define MOVE catgets(catd,1,93,"mPrzem)ie¶æ")
#define COPY catgets(catd,1,94,"kK)opiuj")
#define FILL catgets(catd,1,95,"yWy)pe³nij")
#define MIRROR catgets(catd,1,96,"lOdwróæ (L)ustro)")
#define TOMENU catgets(catd,1,97,"F0, F10 lub / - menu g³ówne")
#define ABOUT catgets(catd,1,98,"wW)ersja")
#define MSHELL catgets(catd,1,99,"oPo)w³oka")
#define MGOTO catgets(catd,1,100,"zPoz)ycja")
#define CWIDTH catgets(catd,1,101,"sS)zeroko¶æ")
#define DELETE catgets(catd,1,102,"sS)kasuj")
#define SORT catgets(catd,1,103,"oSo)rtuj")
#define ADDKEY catgets(catd,1,104,"dD)odaj klawisz")
#define ASCEND catgets(catd,1,105,"rR)osn±co")
#define DESCEND catgets(catd,1,106,"mM)alej±co")
#define SORTIT catgets(catd,1,107,"sS)ortuj zakres")
#define WHOLECOL catgets(catd,1,108,"cC)a³± kolumnê")
#define WHOLELINE catgets(catd,1,109,"cC)a³y wiersz")
#define WHOLELAYER catgets(catd,1,110,"cC)a³y arkusz")
#define SINGLECELL catgets(catd,1,111,"pP)ojedyñcz± komórkê")
#define BLOCK catgets(catd,1,112,"bB)lok")
#define LOADXSHEET catgets(catd,1,113,"Wczytaæ arkusz z pliku XDR:")
#define LOADPSHEET catgets(catd,1,114,"Wczytaæ arkusz z pliku ASCII:")
#define LOADCSVSHEET catgets(catd,1,115,"Wczytaæ arkusz z pliku CSV:")
#define LOADSCSHEET catgets(catd,1,116,"Wczytaæ arkusz z pliku SC:")
#define LOADWK1SHEET catgets(catd,1,117,"Wczytaæ arkusz z pliku WK1:")
#define SAVEXSHEET catgets(catd,1,118,"Zapisaæ arkusz jako plik XDR:")
#define WROTECELLS catgets(catd,1,119,"zapisano zawarto¶æ %u komórek")
#define SAVEPSHEET catgets(catd,1,120,"Zapisaæ arkusz jako plik ASCII:")
#define SAVEMENU catgets(catd,1,121,"Format zapisywanego pliku:")
#define LOADMENU catgets(catd,1,122,"Format wczytywanego pliku:")
#define NAMESHEET catgets(catd,1,123,"Nowa nazwa pliku:")
#define FILERMENU catgets(catd,1,124,"Plik:")
#define LOADANYWAY catgets(catd,1,125,"Bie¿±cy arkusz zmodyfikowano - jednak wczytaæ nowy plik?")
#define LEAVE catgets(catd,1,126,"Bie¿±cy arkusz zmodyfikowano - koñczyæ bez zapisu?")
#define MAINMENU catgets(catd,1,127,"Menu g³ówne:")
#define COLWIDTH catgets(catd,1,128,"Szeroko¶æ kolumny:")
#define CELLATTR catgets(catd,1,129,"Atrybuty komórki:")
#define SHADOWCELL catgets(catd,1,130,"Ukryj komórkê:")
#define TRANSCELL catgets(catd,1,131,"Nadaæ komórce przejrzysto¶æ:")
#define TRANSCUBE catgets(catd,1,132,"Nadaæ blokowi przejrzysto¶æ:")
#define CONTENTS catgets(catd,1,133,"Zawarto¶æ komórki:")
#define CCONTENTS catgets(catd,1,134,"Zawarto¶æ komórki taktowanej:")
#define GOTO catgets(catd,1,135,"Przejd¼ na pozycjê:")
#define LOCBOO catgets(catd,1,136,"¬le okre¶lona pozycja")
#define SHADOWBOO catgets(catd,1,137,"Niemo¿liwe ukrycie komórek z kolumny 0")
#define WHAT catgets(catd,1,138,"Nierozpoznany rozkaz trybu wsadowego:")
#define PRECCELL catgets(catd,1,139,"Dok³adno¶æ w komórce:")
#define PRECBLOCK catgets(catd,1,140,"Dok³adno¶æ w bloku:")
#define SAVETEXTF catgets(catd,1,141,"Zapisz jako czysty tekst w pliku:")
#define SAVECSVF catgets(catd,1,142,"Zapisz w formacie CSV w pliku:")
#define SAVETBLF catgets(catd,1,143,"Zapisz w formacie tbl w pliku:")
#define SAVELATEXF catgets(catd,1,144,"Zapisz w formacie LaTeX w pliku:")
#define SAVEHTMLF catgets(catd,1,145,"Zapisz w formacie HTML w pliku:")
#define SAVECONTEXTF catgets(catd,1,146,"Zapisz w formacie ConTeXt w pliku:")
#define BLOCKATTR catgets(catd,1,147,"Atrybut bloku:")
#define CLEARBLOCK catgets(catd,1,148,"Wyczy¶æ blok:")
#define CLEARCELL catgets(catd,1,149,"Wyczy¶æ komórkê:")
#define SHADOWCUBE catgets(catd,1,150,"Ukryj blok:")
#define INSERTBLOCK catgets(catd,1,151,"Wstaw:")
#define DELETEBLOCK catgets(catd,1,152,"Usuñ:")
#define MODIFYCELL catgets(catd,1,153,"Edycja zawarto¶ci komórki:")
#define LOCKCELL catgets(catd,1,154,"Zabezpiecz komórkê:")
#define LOCKBLOCK catgets(catd,1,155,"Zabezpiecz blok:")
#define IGNCELL catgets(catd,1,156,"Zignoruj zawarto¶æ komórki:")
#define IGNBLOCK catgets(catd,1,157,"Zignoruj zawarto¶ci wszystkich komórek bloku:")
#define DOLABEL catgets(catd,1,158,"Etykieta komórki:")
#define MOVEBLOCK catgets(catd,1,159,"Przemie¶æ blok:")
#define NOMARK catgets(catd,1,160,"Nie zaznaczono bloku")
#define COPYBLOCK catgets(catd,1,161,"Kopiuj blok:")
#define FILLBLOCK catgets(catd,1,162,"Wype³nij blok:")
#define FILLCOLS catgets(catd,1,163,"Ilo¶æ powtórzeñ kolumnami:")
#define FILLROWS catgets(catd,1,164,"Ilo¶æ powtórzeñ wierszami:")
#define FILLLAYERS catgets(catd,1,165,"Ilo¶æ powtórzeñ g³êboko¶ciami:")
#define SORTBLOCK catgets(catd,1,166,"Sortowanie bloku:")
#define XPOS catgets(catd,1,167,"Pozycja X wektora-klucza:")
#define YPOS catgets(catd,1,168,"Pozycja Y wektora-klucza:")
#define ZPOS catgets(catd,1,169,"Pozycja Z wektora-klucza:")
#define MIRRORBLOCK catgets(catd,1,170,"Odwróæ blok (lustro):")
#define LEFTRIGHT catgets(catd,1,171,"lL)ewo-prawo")
#define UPSIDEDOWN catgets(catd,1,172,"gG)óra-dó³")
#define FRONTBACK catgets(catd,1,173,"pP)rzód-ty³")
#define STANDALONE catgets(catd,1,174,"Zapisz jako dokument samodzielny:")
#define BLOCKMENU catgets(catd,1,175,"Menu operacji na blokach:")
#define NOSHADOW catgets(catd,1,176,"Ilo¶æ ukrytych komórek pierwszej kolumny")
#define INVALPRECISION catgets(catd,1,177,"teapot: dok³adno¶æ musi zawieraæ siê pomiêdzy 0 a %d.\n")
#define USAGE_ERROR catgets(catd,1,178,"Wywo³anie: error(³añcuch znakowy informacji)")
#define USAGE_ADR catgets(catd,1,179,"Wywo³anie: &([l.ca³kowita x][,[l.ca³kowita y][,[l.ca³kowita z]]])")
#define USAGE_AT catgets(catd,1,180,"Wywo³anie: @([l.ca³kowita x][,[l.ca³k. y][,[l.ca³k. z]]]) albo @(pozycja)")
#define XTYPE catgets(catd,1,181,"Wywo³anie: x([pozycja])")
#define YTYPE catgets(catd,1,182,"Wywo³anie: y([pozycja])")
#define ZTYPE catgets(catd,1,183,"Wywo³anie: z([pozycja])")
#define STRINGTYPE catgets(catd,1,184,"Wywo³anie: string(pozycja) oder string(l.zmiennoprz.[,[l.ca³k.][,l.ca³k.]])")
#define SUMTYPE catgets(catd,1,185,"Wywo³anie: sum(pozycja,pozycja)")
#define NTYPE catgets(catd,1,186,"Wywo³anie: n(pozycja,pozycja)")
#define INTTYPE catgets(catd,1,187,"Wywo³anie: int(l.zmiennoprzecinkowa[,l.ca³kowita,l.ca³kowita])")
#define FRACTYPE catgets(catd,1,188,"Wywo³anie: frac(l.zmiennoprzecinkowa)")
#define LENTYPE catgets(catd,1,189,"Wywo³anie: len(³añcuch znakowy)")
#define MINTYPE catgets(catd,1,190,"Wywo³anie: min(pozycja,pozycja)")
#define MAXTYPE catgets(catd,1,191,"Wywo³anie: max(pozycja,pozycja)")
#define ABSTYPE catgets(catd,1,192,"Wywo³anie: abs(l.zmiennoprzecinkowa|l.ca³kowita)")
#define USAGE_EVAL catgets(catd,1,193,"Wywo³anie: eval(pozycja)")
#define USAGE_ENV catgets(catd,1,194,"Wywo³anie: $(³añcuch znakowy)")
#define FLOATTYPE catgets(catd,1,195,"Wywo³anie: float(³añcuch znakowy)")
#define STRFTIMETYPE catgets(catd,1,196,"Wywo³anie: strftime(³añcuch znakowy[,l.ca³kowita])")
#define CLOCK catgets(catd,1,197,"Wywo³anie: clock(warunek,pozycja[,pozycja])")
#define POLYTYPE catgets(catd,1,198,"Wywo³anie: poly(l.zmiennoprzecinkowa|l.ca³kowita,l.zmiennoprz.|l.ca³k.,...)")
#define ETYPE catgets(catd,1,199,"Wywo³anie: e()")
#define LOGTYPE catgets(catd,1,200,"Wywo³anie: log(l.zmiennoprzecinkowa[,l.zmiennoprzecinkowa])")
#define WRONGTYPE catgets(catd,1,201,"Wywo³anie: %s(l.zmiennoprzecinkowa)")
#define USAGE_RND catgets(catd,1,202,"Wywo³anie: rnd()")
#define USAGE_SUBSTR catgets(catd,1,203,"Wywo³anie: substr(³añcuch znakowy,l.ca³kowita,l.ca³kowita)")
#define STRPTIMETYPE catgets(catd,1,204,"Wywo³anie: strptime(³añcuch znakowy,³añcuch znakowy)")
#define USAGE_TIME catgets(catd,1,205,"Wywo³anie: time()")

#endif
