#ifndef CAT_H
#define CAT_H

#include <nl_types.h>

#define USAGE catgets(catd,1,1,"Використання teapot [-a] [-b] [-n] [-r] [-p цифри] [файл]\n")
#define OHWELL catgets(catd,1,2,"ПОМИЛКА")
#define DIV0 catgets(catd,1,3,"д╕лення на 0")
#define DIVTYPE catgets(catd,1,4,"неправильн╕ типи для оператора /")
#define MOD0 catgets(catd,1,5,"д╕лення по модулю 0")
#define MODTYPE catgets(catd,1,6,"неправильн╕ типи для оператора %")
#define MULTYPE catgets(catd,1,7,"неправильн╕ типи для оператора *")
#define ADDTYPE catgets(catd,1,8,"неправильн╕ типи для оператора +")
#define SUBTYPE catgets(catd,1,9,"неправильн╕ типи для оператора -")
#define NEGTYPE catgets(catd,1,10,"неправильний тип для оператора -")
#define POWTYPE catgets(catd,1,11,"неправильн╕ типи для оператора ^")
#define MISSOPR catgets(catd,1,12,"пропущений оператор")
#define TOOMANY catgets(catd,1,13,"забагато параметр╕в")
#define NESTEVAL catgets(catd,1,14,"вкладений eval()")
#define CPEXPCT catgets(catd,1,15,"оч╕кувалася ) ")
#define OPEXPECT catgets(catd,1,16,"оч╕кувалася (")
#define VLEXPCT catgets(catd,1,17,"оч╕кувалося значення")
#define PARSERR catgets(catd,1,18,"помилка розбору п╕сля елементу")
#define NOINT catgets(catd,1,19,"int(рядок): неправильний рядок")
#define INFINT catgets(catd,1,20,"int(рядок): domain error")
#define RELTYPE catgets(catd,1,21,"type mismatch for relational operator")
#define NOLABEL catgets(catd,1,22,"Нема╓ тако╖ м╕тки")
#define NEGLOC catgets(catd,1,23,"В╕д'╓мний ╕ндекс")
#define POW00 catgets(catd,1,24,"0^0 не визначено")
#define POWDOM catgets(catd,1,25,"^ caused a domain error")
#define ISLOCKED catgets(catd,1,26,"Ком╕рка замкнена")
#define NOTAG catgets(catd,1,27,"Нев╕домий те╜ %c в %d-му рядку")
#define MOVEONLY catgets(catd,1,28,"П")
#define MOVEEDIT catgets(catd,1,29,"Р")
#define SHADOWBOO2 catgets(catd,1,30,"Намагаюся сховати у т╕нь ком╕рку (%d,%d,%d) у %d-му рядку")
#define XERR catgets(catd,1,31,"Помилка розбору позиц╕╖ x-координати в %d-му рядку")
#define YERR catgets(catd,1,32,"Помилка розбору позиц╕╖ y-координати в %d-му рядку")
#define ZERR catgets(catd,1,33,"Помилка розбору позиц╕╖ z-координати в %d-му рядку")
#define OPTERR catgets(catd,1,34,"Неправильний параметр %c в %d-му рядку")
#define SYNERR catgets(catd,1,35,"Помилка синтаксису виразу у %d-му рядку")
#define WIDTHERR catgets(catd,1,36,"Помилка розбору ширини у %d-му рядку")
#define PRECERR catgets(catd,1,37,"Помилка розбору точност╕ у %d-му рядку")
#define ADJERR catgets(catd,1,38,"Помилка розбору вир╕внювання у %d-му рядку")
#define SCFEATURE catgets(catd,1,39,"Нереал╕зована можлив╕сть SC у %d-му рядку")
#define NOTFINITE catgets(catd,1,40,"Не (ск╕нченне) число з плаваючою комою")
#define UFLOW catgets(catd,1,41,"Втрата значення числа з плаваючою комою")
#define OFLOW catgets(catd,1,42,"Переповнення числа з плаваючою комою")
#define UNCOMPAR catgets(catd,1,43,"непор╕вняльн╕ елементи")
#define NOREGION catgets(catd,1,44,"Не вибрано область")
#define SHELL catgets(catd,1,45,"Породжую п╕доболнку")
#define SUBSHELL catgets(catd,1,46,"П╕доболонка запущена")
#define BACKGROUND catgets(catd,1,47,"Teapot зупинений")
#define NOTSUSPENDED catgets(catd,1,48,"The susp character is undefined")
#define BROKENSHEET catgets(catd,1,49,"Неправильний запис, завантаження припинено")
#define WRONGXDRMAGIC catgets(catd,1,50,"Це не таблиця Teapot-а у формат╕ XDR")
#define TRUNCHEADER catgets(catd,1,51,"Заголовок запису виявився обр╕заним")
#define TRUNCBODY catgets(catd,1,52,"Т╕ло запису виявилося обр╕заним")
#define NOBOF catgets(catd,1,53,"Це не файл у формат╕ WK1")
#define NOEOF catgets(catd,1,54,"Файл обр╕заний")
#define INVALIDBODYLEN catgets(catd,1,55,"Неправильна довжина т╕ла запису")
#define NOMEM catgets(catd,1,56,"Пам'ять вичерапана")
#define YES catgets(catd,1,57,"yY)Так")
#define NO catgets(catd,1,58,"nN)Н╕")
#define ADJUST catgets(catd,1,59,"rR)Представлення")
#define ADLEFT catgets(catd,1,60,"lL)Нал╕во")
#define ADRIGHT catgets(catd,1,61,"rR)Направо")
#define ADCENTERED catgets(catd,1,62,"cC)В╕дцентрувати")
#define PRECISION catgets(catd,1,63,"pP)Точн╕сть")
#define DOLOCK catgets(catd,1,64,"oO)Замкнути")
#define DOIGNORE catgets(catd,1,65,"iI)╤гнорувати")
#define DOSCI catgets(catd,1,66,"00).123e1")
#define NOSCI catgets(catd,1,67,"11).23")
#define LABEL catgets(catd,1,68,"lL)М╕тка")
#define ASXDR catgets(catd,1,69,"xX)XDR")
#define ASASCII catgets(catd,1,70,"aA)Текст")
#define ASSC catgets(catd,1,71,"sS)SC")
#define ASWK1 catgets(catd,1,72,"wW)WK1")
#define TBL catgets(catd,1,73,"tT)Таблиця")
#define LATEX catgets(catd,1,74,"lL)LaTeX")
#define HTML catgets(catd,1,75,"hH)HTML")
#define CSV catgets(catd,1,76,"cC)CSV")
#define GCSV catgets(catd,1,77,"cG)GCSV")
#define SAVETEXT catgets(catd,1,78,"fF)Форматований текст")
#define CONTEXT catgets(catd,1,79,"oCo)nTeXt")
#define LOAD catgets(catd,1,80,"lL)Завантажити")
#define SAVE catgets(catd,1,81,"sS)Зберегти")
#define NAME catgets(catd,1,82,"nN)╤м'я")
#define FILER catgets(catd,1,83,"fF)Файл")
#define QUIT catgets(catd,1,84,"qQ)Вих╕д")
#define ATTR catgets(catd,1,85,"aA)Атрибути")
#define SHADOW catgets(catd,1,86,"sS)Т╕нь")
#define TRANSPAR catgets(catd,1,87,"oO)Вив╕д спец╕альних символ╕в")
#define INX catgets(catd,1,88,"cC)Стовпчик")
#define INY catgets(catd,1,89,"rR)Рядок")
#define INZ catgets(catd,1,90,"dD)Глибина")
#define INSERT catgets(catd,1,91,"iI)Вставити")
#define CLEAR catgets(catd,1,92,"eE)Очистити")
#define MOVE catgets(catd,1,93,"mM)Перенести")
#define COPY catgets(catd,1,94,"cC)Скоп╕ювати")
#define FILL catgets(catd,1,95,"fF)Заповнити")
#define MIRROR catgets(catd,1,96,"rR)Зеркало")
#define TOMENU catgets(catd,1,97,"Використовуйте <F10>, <F0> чи </> для доступу до меню")
#define ABOUT catgets(catd,1,98,"vV)Верс╕я")
#define MSHELL catgets(catd,1,99,"sS)Оболонка")
#define MGOTO catgets(catd,1,100,"gG)Перейти")
#define CWIDTH catgets(catd,1,101,"wW)Ширина")
#define DELETE catgets(catd,1,102,"dD)Видалити")
#define SORT catgets(catd,1,103,"sS)Сортування")
#define ADDKEY catgets(catd,1,104,"aA)Додати ключ")
#define ASCEND catgets(catd,1,105,"aA)За зростанням")
#define DESCEND catgets(catd,1,106,"dD)За спаданням")
#define SORTIT catgets(catd,1,107,"sS)В╕дсортувати область")
#define WHOLECOL catgets(catd,1,108,"wW)Весь стовпчик")
#define WHOLELINE catgets(catd,1,109,"wW)Весь рядок")
#define WHOLELAYER catgets(catd,1,110,"wW)Всю таблицю")
#define SINGLECELL catgets(catd,1,111,"sS)Одну ком╕рку")
#define BLOCK catgets(catd,1,112,"bB)Блок")
#define LOADXSHEET catgets(catd,1,113,"Завантажити лист з файлу формату XDR:")
#define LOADPSHEET catgets(catd,1,114,"Завантажити лист з текстового файлу:")
#define LOADCSVSHEET catgets(catd,1,115,"Завантажити лист з файлу у формат╕ CSV:")
#define LOADSCSHEET catgets(catd,1,116,"Завантажити лист з файлу формату SC:")
#define LOADWK1SHEET catgets(catd,1,117,"Завантажити лист з файлу формату WK1:")
#define SAVEXSHEET catgets(catd,1,118,"Зберегти лист у файл формату XDR:")
#define WROTECELLS catgets(catd,1,119,"%u ком╕рок записано")
#define SAVEPSHEET catgets(catd,1,120,"Зберегти лист у текстовий файл:")
#define SAVEMENU catgets(catd,1,121,"Формат файл для збереження листа:")
#define LOADMENU catgets(catd,1,122,"Формат файл для завантаження листа:")
#define NAMESHEET catgets(catd,1,123,"╤м'я нового файлу:")
#define FILERMENU catgets(catd,1,124,"Файл:")
#define LOADANYWAY catgets(catd,1,125,"Лист модиф╕ковано, завантажити новий файл всеодно?")
#define LEAVE catgets(catd,1,126,"Лист модиф╕ковано, залишити всеодно?")
#define MAINMENU catgets(catd,1,127,"Головне меню:")
#define COLWIDTH catgets(catd,1,128,"Ширина стовпчика:")
#define CELLATTR catgets(catd,1,129,"Атрибут ком╕рки:")
#define SHADOWCELL catgets(catd,1,130,"Т╕ньова ком╕рка:")
#define TRANSCELL catgets(catd,1,131,"Зробити ком╕рку прозорою:")
#define TRANSCUBE catgets(catd,1,132,"Зробити блок прозорим:")
#define CONTENTS catgets(catd,1,133,"Вм╕ст ком╕рки:")
#define CCONTENTS catgets(catd,1,134,"Clocked cell contents:")
#define GOTO catgets(catd,1,135,"Перейти до позиц╕╖:")
#define LOCBOO catgets(catd,1,136,"Неправильна позиц╕я")
#define SHADOWBOO catgets(catd,1,137,"Ви не можете сховати у т╕нь ком╕рки у 0-му стовпц╕")
#define WHAT catgets(catd,1,138,"Нев╕дома пакетна команда:")
#define PRECCELL catgets(catd,1,139,"Точн╕сть для ком╕рки:")
#define PRECBLOCK catgets(catd,1,140,"Точн╕сть для блоку:")
#define SAVETEXTF catgets(catd,1,141,"Зберегти у простому текстовому файл╕:")
#define SAVECSVF catgets(catd,1,142,"Зберегти у формат╕ CSV у файл:")
#define SAVETBLF catgets(catd,1,143,"Зберегти у формат╕ tbl у файл:")
#define SAVELATEXF catgets(catd,1,144,"Зберегти у формат╕ LaTeX у файл:")
#define SAVEHTMLF catgets(catd,1,145,"Зберегти у формат╕ HTML у файл:")
#define SAVECONTEXTF catgets(catd,1,146,"Зберегти у формат╕ ConTeXt у файл:")
#define BLOCKATTR catgets(catd,1,147,"Атрибут блоку:")
#define CLEARBLOCK catgets(catd,1,148,"Очистити блок:")
#define CLEARCELL catgets(catd,1,149,"Очистити ком╕рку:")
#define SHADOWCUBE catgets(catd,1,150,"Сховати у т╕нь блок:")
#define INSERTBLOCK catgets(catd,1,151,"Вставити:")
#define DELETEBLOCK catgets(catd,1,152,"Видалити:")
#define MODIFYCELL catgets(catd,1,153,"Редагувати ком╕рку:")
#define LOCKCELL catgets(catd,1,154,"Замкнути ком╕рку:")
#define LOCKBLOCK catgets(catd,1,155,"Замкнути блок:")
#define IGNCELL catgets(catd,1,156,"╤гнорувати значення ком╕рки:")
#define IGNBLOCK catgets(catd,1,157,"╤гнорувати значення ус╕х ком╕рок у цьому блоц╕:")
#define DOLABEL catgets(catd,1,158,"М╕тка ком╕рки:")
#define MOVEBLOCK catgets(catd,1,159,"Перенести блок:")
#define NOMARK catgets(catd,1,160,"Блок не в╕дм╕чено")
#define COPYBLOCK catgets(catd,1,161,"Скоп╕ювати блок:")
#define FILLBLOCK catgets(catd,1,162,"Заповнити блок:")
#define FILLCOLS catgets(catd,1,163,"К╕льк╕сть повторень для стовпц╕в:")
#define FILLROWS catgets(catd,1,164,"К╕льк╕сть повторень для рядк╕в:")
#define FILLLAYERS catgets(catd,1,165,"К╕льк╕сть повторень для шар╕в:")
#define SORTBLOCK catgets(catd,1,166,"В╕дсортувати блок:")
#define XPOS catgets(catd,1,167,"позиц╕я X ключового вектора:")
#define YPOS catgets(catd,1,168,"позиц╕я Y ключового вектора:")
#define ZPOS catgets(catd,1,169,"позиц╕я Z ключового вектора:")
#define MIRRORBLOCK catgets(catd,1,170,"В╕дзеркалити блок:")
#define LEFTRIGHT catgets(catd,1,171,"lL)Зл╕ва-направо")
#define UPSIDEDOWN catgets(catd,1,172,"uU)Зверху-вниз")
#define FRONTBACK catgets(catd,1,173,"fF)Спереду-назад")
#define STANDALONE catgets(catd,1,174,"Зберегти як окремий документ:")
#define BLOCKMENU catgets(catd,1,175,"Меню блоку:")
#define NOSHADOW catgets(catd,1,176,"Т╕ньов╕ ком╕рки у першому стовпц╕")
#define INVALPRECISION catgets(catd,1,177,"teapot: точн╕сть повинна бути м╕ж 0 ╕ %d.\n")
#define USAGE_ERROR catgets(catd,1,178,"Використання: error(рядок пов╕домлення)")
#define USAGE_ADR catgets(catd,1,179,"Використання: &([ц╕ле x][,[ц╕ле y][,[ц╕ле z]]])")
#define USAGE_AT catgets(catd,1,180,"Використання: @([ц╕ле x][,[ц╕ле y][,[ц╕ле z]]]) or @(позиц╕я)")
#define XTYPE catgets(catd,1,181,"Використання: x([позиц╕я])")
#define YTYPE catgets(catd,1,182,"Використання: y([позиц╕я])")
#define ZTYPE catgets(catd,1,183,"Використання: z([позиц╕я])")
#define STRINGTYPE catgets(catd,1,184,"Використання: location(позиц╕я) або location(дробове[,[ц╕ле][,ц╕ле]])")
#define SUMTYPE catgets(catd,1,185,"Використання: sum(позиц╕я,позиц╕я)")
#define NTYPE catgets(catd,1,186,"Використання: n(позиц╕я,позиц╕я)")
#define INTTYPE catgets(catd,1,187,"Використання: int(дробове[,ц╕ле,ц╕ле])")
#define FRACTYPE catgets(catd,1,188,"Використання: frac(дробове)")
#define LENTYPE catgets(catd,1,189,"Використання: len(рядок)")
#define MINTYPE catgets(catd,1,190,"Використання: min(позиц╕я,позиц╕я)")
#define MAXTYPE catgets(catd,1,191,"Використання: max(позиц╕я,позиц╕я)")
#define ABSTYPE catgets(catd,1,192,"Використання: abs(дробове|ц╕ле)")
#define USAGE_EVAL catgets(catd,1,193,"Використання: eval(позиц╕я)")
#define USAGE_ENV catgets(catd,1,194,"Використання: $(рядок)")
#define FLOATTYPE catgets(catd,1,195,"Використання: float(рядок)")
#define STRFTIMETYPE catgets(catd,1,196,"Використання: strftime(рядок[,ц╕ле])")
#define CLOCK catgets(catd,1,197,"Використання: clock(condition,позиц╕я[,позиц╕я])")
#define POLYTYPE catgets(catd,1,198,"Використання: poly(дробове|ц╕ле,дробове|ц╕ле,...)")
#define ETYPE catgets(catd,1,199,"Використання: e()")
#define LOGTYPE catgets(catd,1,200,"Використання: log(дробове[,дробове])")
#define WRONGTYPE catgets(catd,1,201,"Використання: %s(дробове)")
#define USAGE_RND catgets(catd,1,202,"Використання: rnd()")
#define USAGE_SUBSTR catgets(catd,1,203,"Використання: substr(рядок,ц╕ле,ц╕ле)")
#define STRPTIMETYPE catgets(catd,1,204,"Використання: strptime(рядок,рядок)")
#define USAGE_TIME catgets(catd,1,205,"Використання: time()")

#endif
