#!/bin/sh
awk '
/<pre>/{
	pre = 1
}
/<\/pre>/{
	pre = 0 
}
/$/ {
	if (pre) printf("%s<br>\n", $0) 
	else printf("%s\n",$0)
}
' < doc/teapot.html | sed -e '
	s/\\/\\\\/g;
	s/\&\([^a-z]\)/\&amp;\1/g;
	s/<a href="\([^"]*\)">\(.*\)<\/a>/\2 (\1)/g;
	s/<\/\?\(html\|body\|address\|center\|dl\|ul\|a\)>//g;
	s/<head>.*<\/head>//g;
	s/<\(\/\?\)\(pre\|table\)>/<\1tt>\\n\\n/g;
	s/<\(\/\?\)\(code\|kbd\)>/<\1tt>/g;
	s/<\(\/\?\)\(em\|var\)>/<\1i>/g;
	s/<dt>/\\n<b>/g;
	s/<dd>/<\/b>\\n/g;
	s/<h1>/\\n<big><b>/g;
	s/<\/h1>/<\/b><\/big>\\n\\n<small>Please note: This manual refers to the terminal version of teapot, so menu layout and key bindings will differ. See the GUI menu for key bindings.<\/small>\\n\\n/g;
	s/<h2>/\\n\\n<big>/g;
	s/<\/h2>/<\/big>\\n/g;
	s/<h3>/\\n\\n<b>/g;
	s/<\/h3>/<\/b>\\n/g;
	s/<h4>/\\n\\n/g;
	s/<\(blockquote\|tr\|td\)[^>]*>//g;
	s/<\/\(blockquote\|h4\)>/\\n/g;
	s/<p>/\\n\\n/g;
	s/<br>/\\n/g;
	s/<\/td>/		/g;
	s/<li>/\\n <b>*<\/b> /g;
	s/<\/tr>/\\n/g;
	s/<\([^a-z/]\)/\&lt;\1/g;
	s/"/\\"/g;
	s/%/%%/g;
	s/^/"/;
	s/$/ "/;
' > help.h